# Load the zshrc_local file if it exists
if [ -f "$HOME/.zshrc_local" ]; then
	source "$HOME/.zshrc_local"
fi

if [ -f "$HOME/.zshrc_dev" ]; then
	source "$HOME/.zshrc_dev"
fi

alias vim=nvim
alias cat=bat
alias du=dust
alias find=fd
alias grep=rg
alias ls=lsd
alias ps=procs
alias sed=sd
alias top=btm

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git macos)

source "$ZSH/oh-my-zsh.sh"

[ -f "$HOME/.config/broot/launcher/bash/br" ] && source "$HOME/.config/broot/launcher/bash/br"

command -v mcfly &> /dev/null && eval "$(mcfly init zsh)"
command -v zoxide &> /dev/null && eval "$(zoxide init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
